### ISSUE TITLE
can't run because can't install module  Contextual::Return in strawberry perl

### ISSUE THREAD

**Issue by zaiai2003** [caseycole589/MojoDojo#1]
D:\dojo\MojoDojo-master>cpanm DBIx::Class::InflateColumn::Boolean
--> Working on DBIx::Class::InflateColumn::Boolean
Fetching http://www.cpan.org/authors/id/G/GR/GRAF/DBIx-Class-InflateColumn-Boole
an-0.002000.tar.gz ... OK
Configuring DBIx-Class-InflateColumn-Boolean-0.002000 ... OK
==> Found dependencies: Contextual::Return
--> Working on Contextual::Return
Fetching http://www.cpan.org/authors/id/D/DC/DCONWAY/Contextual-Return-0.004007.
tar.gz ... OK
Configuring Contextual-Return-0.004007 ... OK
Building and testing Contextual-Return-0.004007 ... OK
Successfully installed Contextual-Return-0.004007
! Installing the dependencies failed: Missing version info for module 'Contextua
l::Return'
! Bailing out the installation for DBIx-Class-InflateColumn-Boolean-0.002000.
1 distribution installed

**Comment by caseycole589** [comment]
if your on linux see if the package is in your distro the DBIx InlfateColumn boolean is not a much needed  to get it to work.

**Comment by caseycole589** [comment]
I don't use perl on windows so, I can't help you. I don't think The server will work either you will have much better luck using cygwin on windows. Sorry for late response.
